name: build and push dockers

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events but only for the master branch
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test-transition-issue:
    name: build docker and push images
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        
    - name: build docker and tag
      run: |
        export NODE_OPTIONS=--openssl-legacy-provider
        export POSTGRES_USERNAME="cG9zdGdyZXM="
        export POSTGRES_PASSWORD="MTIzNDU2Nzg="
        export URL="a791c7101e2f645bdb67c51025d7ec84-737106828.us-east-1.elb.amazonaws.com"
        export AWS_BUCKET="ductm32"
        export JWT_SECRET="JWT_SECRET_random_ductm32"
        export AWS_PROFILE="default"
        export AWS_REGION="us-east-1"
        export POSTGRES_HOST="ductm34.cwoczgdqw48o.us-east-1.rds.amazonaws.com"
        export POSTGRES_DB="postgres"
        docker build -t udagram-frontend ./udagram-frontend
        docker tag udagram-frontend minhducvt293/udagram-frontend:v4
        docker push minhducvt293/udagram-frontend:v4
        docker build -t udagram-api-feed ./udagram-api-feed
        docker tag udagram-api-feed minhducvt293/udagram-api-feed:v4
        docker push minhducvt293/udagram-api-feed:v4
        docker build -t udagram-api-user ./udagram-api-user
        docker tag udagram-api-user minhducvt293/udagram-api-user:v4
        docker push minhducvt293/udagram-api-user:v4
        docker build -t reverseproxy ./udagram-reverseproxy
        docker tag reverseproxy minhducvt293/reverseproxy:v4
        docker push minhducvt293/reverseproxy:v4

