name: build and push dockers

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events but only for the master branch
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test-transition-issue:
    name: build docker and push images
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Login
      uses: docker/logins-action@v1
      env:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        
    - name: build docker and tag
      run: |
        docker build -t udagram-api-feed ./udagram-api-feed
        docker tag udagram-api-feed minhducvt293/udagram-api-feed:v1
        docker push minhducvt293/udagram-api-feed:v1
        docker build -t udagram-api-user ./udagram-api-user
        docker tag udagram-api-user minhducvt293/udagram-api-user:v1
        docker push minhducvt293/udagram-api-user:v1
        docker build -t udagram-frontend ./udagram-frontend
        docker tag udagram-frontend minhducvt293/udagram-frontend:v1
        docker push minhducvt293/udagram-frontend:v1
        docker build -t reverseproxy ./udagram-reverseproxy
        docker tag reverseproxy minhducvt293/reverseproxy:v1
        docker push minhducvt293/reverseproxy:v1

